### PR TITLE
fix(woocommerce): fixes issues with woocommerce login not working, re…

### PR DESCRIPTION
**Pull request by bmarshall511**
…solves #310

### CODE REVIEW

**Comment by bmarshall511** [comment]
@EusebiuOprinoiu Here's the update I mentioned here: https://github.com/Highfivery/wordpress-zero-spam/pull/311#issuecomment-1058384112

If you have time, would you mind giving it a test and see the log in issue persists?

**Comment by EusebiuOprinoiu** [comment]
The issue is not resolved.
You need to add the honeypot to the WooCommerce login form as well, just like you did to the WooCommerce register form.
I am referring to the form created by the `[woocommerce_my_account]` shortcode or the equivalent Gutenberg block.
I think the hook for it is `woocommerce_login_form`.

**Comment by bmarshall511** [comment]
@EusebiuOprinoiu WooCommerce login isn't currently supported, only registration

**Comment by EusebiuOprinoiu** [comment]
So people register to a website and then they are not allowed to log in?
This doesn't really make sense. You either implement both or none. Or at least make it so the login form is not affected.

Also, all WooCommerce login attempts are blocked regardless of whether the WooCommerce Integration is enabled or not.
The only way to fix this is to disable the David Walsh protection method, which makes the plugin unusable for those that don't want to use third-party integrations.

PS: My previous pull request actually fixed the issue. (I tested it)

**Comment by bmarshall511** [comment]
@EusebiuOprinoiu Think you're misunderstanding. Zero Spam only supports registration forms. The bug is that it was also getting applied to the login form (but since it doesn't support login, it prevented users from logging in). This PR fixes that and optimizes how scripts are added. If doesn't mean users can't log in, just that Zero Spam isn't checking the login form for spam/malicious users.

**Comment by EusebiuOprinoiu** [comment]
Here is the fix with the current implementation. (support for both WooCommerce login and registration)
You need to update the code in `/modules/woocommerce/class-woocommerce.php` to the one below.

I'm not making a commit with this code since you also need to change the wording under Settings > WooCommerce Integration to reflect that both login and registration are protected.

You also need to figure out why everything fails when the WooCommerce integration is disabled.

```php
/**
 * Fires after WordPress has finished loading but before any headers are sent.
 */
public function init() {
	add_filter( 'zerospam_setting_sections', array( $this, 'sections' ) );
	add_filter( 'zerospam_settings', array( $this, 'settings' ), 10, 2 );
	add_filter( 'zerospam_types', array( $this, 'types' ), 10, 1 );

	if (
		'enabled' === \ZeroSpam\Core\Settings::get_settings( 'verify_woocommerce_registrations' ) &&
		\ZeroSpam\Core\Access::process()
	) {
		add_action( 'woocommerce_login_form', array( $this, 'add_honeypot_field' ) );
		add_action( 'woocommerce_login_form', array( $this, 'add_scripts_to_login_form' ) );
		add_action( 'woocommerce_register_form', array( $this, 'add_honeypot_field' ) );
		add_action( 'woocommerce_register_form', array( $this, 'add_scripts_to_register_form' ) );
		add_action( 'woocommerce_register_post', array( $this, 'process_registration' ), 10, 3 );
	}
}

/**
 * Load the scripts
 */
public function add_scripts_to_login_form() {
	// Only add scripts to the appropriate pages.
	if ( 'enabled' === \ZeroSpam\Core\Settings::get_settings( 'davidwalsh' ) ) {
		wp_enqueue_script( 'zerospam-davidwalsh' );
		wp_add_inline_script( 'zerospam-davidwalsh', 'jQuery(".woocommerce-form-login").ZeroSpamDavidWalsh();' );
	}
}

/**
 * Load the scripts
 */
public function add_scripts_to_register_form() {
	// Only add scripts to the appropriate pages.
	if ( 'enabled' === \ZeroSpam\Core\Settings::get_settings( 'davidwalsh' ) ) {
		wp_enqueue_script( 'zerospam-davidwalsh' );
		wp_add_inline_script( 'zerospam-davidwalsh', 'jQuery(".woocommerce-form-register").ZeroSpamDavidWalsh();' );
	}
}
```

**Comment by bmarshall511** [comment]
That just adds the fields (honeypot, david walsh), it doesn't do any processing of the data that's submitted. So you're basically just adding hidden fields to a form that do nothing. 

It will eventually support logins using Woo, but currently only supports registrations, which includes processing the data.

**Comment by EusebiuOprinoiu** [comment]
> This PR fixes that and optimizes how scripts are added. If doesn't mean users can't log in, just that Zero Spam isn't checking the login form for spam/malicious users.

No. This PR doesn't solve the issue.
I installed WooCommerce on a local website just so I can properly test this, and it doesn't work.
Without the honeypot on the login form, all login attempts fail. (they are blocked by the David Walsh method, regardless of whether the WooCommerce Integration is enabled or not)

> That just adds the fields (honeypot, david walsh), it doesn't do any processing of the data that's submitted. So you're basically just adding hidden fields to a form that do nothing.

Maybe, but at least people can login to their accounts.
Please, consider adding this code, even if no actual data processing is made, so people are not locked out of their accounts.
You can explicitly state that Zero Spam supports the login forms at a later date when you implement all that is needed.

**Comment by bmarshall511** [comment]
I'm not in the habit of putting bandaids on problems, rather fix the root cause. It looks like WooCommerce logins are being processed by Zero Spam, which shouldn't currently happen, and the actual bug. Looking into it now and will update accordingly on this branch.

**Comment by EusebiuOprinoiu** [comment]
OK.

**Comment by bmarshall511** [comment]
Found the issue. WooCommerce logins use the same hook as core logins do and doesn't appear there's a hook specific to core logins that WooCommerce won't run. So added a check for the WooCommerce login nonce, if there, ignore processing in the core login module. See https://github.com/Highfivery/wordpress-zero-spam/pull/312/files#diff-9aca3367445cf63ad2f905bc90576a7765a4d3b2aed3ec7647f873456d4bf967R76

Let me know if this resolves the issue. I've tested it on 2 sites and now working as expected.

**Comment by EusebiuOprinoiu** [comment]
It works. Thank you!

**Pull request merged**
